/**
 * OAuth provider configurations for all 36 connectors
 * Each provider has clientId, clientSecret, and OAuth endpoints
 */

export interface OAuthProviderConfig {
  id: string;
  name: string;
  authorizationUrl: string;
  tokenUrl: string;
  userInfoUrl?: string;
  scopes: string[];
  defaultScopes?: string[];
}

export const OAUTH_PROVIDERS: Record<string, OAuthProviderConfig> = {
  google: {
    id: "google",
    name: "Google",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo",
    scopes: ["email", "profile", "https://www.googleapis.com/auth/gmail.readonly"],
    defaultScopes: ["email", "profile"],
  },
  github: {
    id: "github",
    name: "GitHub",
    authorizationUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    userInfoUrl: "https://api.github.com/user",
    scopes: ["repo", "user", "gist", "read:org"],
    defaultScopes: ["repo", "user"],
  },
  slack: {
    id: "slack",
    name: "Slack",
    authorizationUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    userInfoUrl: "https://slack.com/api/auth.test",
    scopes: ["chat:write", "channels:read", "users:read", "team:read"],
    defaultScopes: ["chat:write", "channels:read"],
  },
  microsoft: {
    id: "microsoft",
    name: "Microsoft",
    authorizationUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    userInfoUrl: "https://graph.microsoft.com/v1.0/me",
    scopes: ["Mail.Read", "Calendar.Read", "User.Read"],
    defaultScopes: ["User.Read"],
  },
  notion: {
    id: "notion",
    name: "Notion",
    authorizationUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    scopes: [],
    defaultScopes: [],
  },
  twitter: {
    id: "twitter",
    name: "Twitter",
    authorizationUrl: "https://twitter.com/i/oauth2/authorize",
    tokenUrl: "https://twitter.com/2/oauth2/token",
    userInfoUrl: "https://api.twitter.com/2/users/me",
    scopes: ["tweet.read", "users.read", "tweet.write"],
    defaultScopes: ["tweet.read", "users.read"],
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    authorizationUrl: "https://www.linkedin.com/oauth/v2/authorization",
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
    userInfoUrl: "https://api.linkedin.com/v2/me",
    scopes: ["r_liteprofile", "r_emailaddress"],
    defaultScopes: ["r_liteprofile"],
  },
  salesforce: {
    id: "salesforce",
    name: "Salesforce",
    authorizationUrl: "https://login.salesforce.com/services/oauth2/authorize",
    tokenUrl: "https://login.salesforce.com/services/oauth2/token",
    userInfoUrl: "https://login.salesforce.com/services/oauth2/userinfo",
    scopes: ["api", "refresh_token"],
    defaultScopes: ["api"],
  },
  hubspot: {
    id: "hubspot",
    name: "HubSpot",
    authorizationUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    userInfoUrl: "https://api.hubapi.com/crm/v3/objects/contacts/search",
    scopes: ["crm.objects.contacts.read", "crm.objects.deals.read"],
    defaultScopes: ["crm.objects.contacts.read"],
  },
  shopify: {
    id: "shopify",
    name: "Shopify",
    authorizationUrl: "https://{{shop}}.myshopify.com/admin/oauth/authorize",
    tokenUrl: "https://{{shop}}.myshopify.com/admin/oauth/access_token",
    scopes: ["read_products", "write_products", "read_orders"],
    defaultScopes: ["read_products", "read_orders"],
  },
  stripe: {
    id: "stripe",
    name: "Stripe",
    authorizationUrl: "https://connect.stripe.com/oauth/authorize",
    tokenUrl: "https://connect.stripe.com/oauth/token",
    userInfoUrl: "https://api.stripe.com/v1/account",
    scopes: [],
    defaultScopes: [],
  },
  discord: {
    id: "discord",
    name: "Discord",
    authorizationUrl: "https://discord.com/api/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    userInfoUrl: "https://discord.com/api/users/@me",
    scopes: ["identify", "email", "guilds", "bot"],
    defaultScopes: ["identify", "email"],
  },
  figma: {
    id: "figma",
    name: "Figma",
    authorizationUrl: "https://www.figma.com/oauth",
    tokenUrl: "https://api.figma.com/v1/oauth/token",
    userInfoUrl: "https://api.figma.com/v1/me",
    scopes: ["file_content_read"],
    defaultScopes: ["file_content_read"],
  },
  jira: {
    id: "jira",
    name: "Jira",
    authorizationUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    userInfoUrl: "https://api.atlassian.com/me",
    scopes: ["read:jira-work", "write:jira-work"],
    defaultScopes: ["read:jira-work"],
  },
  asana: {
    id: "asana",
    name: "Asana",
    authorizationUrl: "https://app.asana.com/-/oauth_authorize",
    tokenUrl: "https://app.asana.com/-/oauth_token",
    userInfoUrl: "https://app.asana.com/api/1.0/users/me",
    scopes: [],
    defaultScopes: [],
  },
  airtable: {
    id: "airtable",
    name: "Airtable",
    authorizationUrl: "https://airtable.com/oauth2/v1/authorize",
    tokenUrl: "https://airtable.com/oauth2/v1/token",
    userInfoUrl: "https://api.airtable.com/v0/meta/whoami",
    scopes: ["data.records:read", "data.records:write"],
    defaultScopes: ["data.records:read"],
  },
  dropbox: {
    id: "dropbox",
    name: "Dropbox",
    authorizationUrl: "https://www.dropbox.com/oauth2/authorize",
    tokenUrl: "https://api.dropboxapi.com/oauth2/token",
    userInfoUrl: "https://api.dropboxapi.com/2/users/get_current_account",
    scopes: ["files.metadata.read", "files.content.read"],
    defaultScopes: ["files.metadata.read"],
  },
  zoom: {
    id: "zoom",
    name: "Zoom",
    authorizationUrl: "https://zoom.us/oauth/authorize",
    tokenUrl: "https://zoom.us/oauth/token",
    userInfoUrl: "https://api.zoom.us/v2/users/me",
    scopes: ["user:read"],
    defaultScopes: ["user:read"],
  },
  twilio: {
    id: "twilio",
    name: "Twilio",
    authorizationUrl: "https://www.twilio.com/oauth/authorize",
    tokenUrl: "https://www.twilio.com/oauth/token",
    scopes: [],
    defaultScopes: [],
  },
  mailchimp: {
    id: "mailchimp",
    name: "Mailchimp",
    authorizationUrl: "https://login.mailchimp.com/oauth/authorize",
    tokenUrl: "https://login.mailchimp.com/oauth/token",
    userInfoUrl: "https://api.mailchimp.com/3.0/",
    scopes: [],
    defaultScopes: [],
  },
  intercom: {
    id: "intercom",
    name: "Intercom",
    authorizationUrl: "https://app.intercom.com/oauth",
    tokenUrl: "https://api.intercom.io/auth/eagle/token",
    scopes: [],
    defaultScopes: [],
  },
  zendesk: {
    id: "zendesk",
    name: "Zendesk",
    authorizationUrl: "https://{{subdomain}}.zendesk.com/oauth/authorizations/new",
    tokenUrl: "https://{{subdomain}}.zendesk.com/oauth/tokens",
    scopes: [],
    defaultScopes: [],
  },
  quickbooks: {
    id: "quickbooks",
    name: "QuickBooks",
    authorizationUrl: "https://appcenter.intuit.com/connect/oauth2",
    tokenUrl: "https://quickbooks.api.intuit.com/oauth2/tokens/bearer",
    userInfoUrl: "https://quickbooks.api.intuit.com/v2/oauth2/tokens/me",
    scopes: [],
    defaultScopes: [],
  },
  xero: {
    id: "xero",
    name: "Xero",
    authorizationUrl: "https://login.xero.com/identity/connect/authorize",
    tokenUrl: "https://identity.xero.com/connect/token",
    userInfoUrl: "https://api.xero.com/api.xro/2.0/Organisation",
    scopes: ["offline_access", "openid", "profile", "email"],
    defaultScopes: ["offline_access"],
  },
  webflow: {
    id: "webflow",
    name: "Webflow",
    authorizationUrl: "https://webflow.com/oauth/authorize",
    tokenUrl: "https://api.webflow.com/oauth/access_token",
    userInfoUrl: "https://api.webflow.com/user",
    scopes: [],
    defaultScopes: [],
  },
  wordpress: {
    id: "wordpress",
    name: "WordPress",
    authorizationUrl: "https://public-api.wordpress.com/oauth2/authorize",
    tokenUrl: "https://public-api.wordpress.com/oauth2/token",
    userInfoUrl: "https://public-api.wordpress.com/rest/v1/me",
    scopes: [],
    defaultScopes: [],
  },
  reddit: {
    id: "reddit",
    name: "Reddit",
    authorizationUrl: "https://www.reddit.com/api/v1/authorize",
    tokenUrl: "https://www.reddit.com/api/v1/access_token",
    userInfoUrl: "https://oauth.reddit.com/api/v1/me",
    scopes: ["identity", "read", "submit"],
    defaultScopes: ["identity"],
  },
  spotify: {
    id: "spotify",
    name: "Spotify",
    authorizationUrl: "https://accounts.spotify.com/authorize",
    tokenUrl: "https://accounts.spotify.com/api/token",
    userInfoUrl: "https://api.spotify.com/v1/me",
    scopes: ["user-read-private", "user-read-email", "playlist-read-private"],
    defaultScopes: ["user-read-private"],
  },
  youtube: {
    id: "youtube",
    name: "YouTube",
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/youtube/v3/channels",
    scopes: ["https://www.googleapis.com/auth/youtube.readonly"],
    defaultScopes: ["https://www.googleapis.com/auth/youtube.readonly"],
  },
  instagram: {
    id: "instagram",
    name: "Instagram",
    authorizationUrl: "https://api.instagram.com/oauth/authorize",
    tokenUrl: "https://graph.instagram.com/v18.0/access_token",
    userInfoUrl: "https://graph.instagram.com/me",
    scopes: ["user_profile", "user_media"],
    defaultScopes: ["user_profile"],
  },
  facebook: {
    id: "facebook",
    name: "Facebook",
    authorizationUrl: "https://www.facebook.com/v18.0/dialog/oauth",
    tokenUrl: "https://graph.facebook.com/v18.0/oauth/access_token",
    userInfoUrl: "https://graph.facebook.com/me",
    scopes: ["email", "public_profile", "pages_manage_metadata"],
    defaultScopes: ["email", "public_profile"],
  },
  tiktok: {
    id: "tiktok",
    name: "TikTok",
    authorizationUrl: "https://www.tiktok.com/v1/oauth/authorize",
    tokenUrl: "https://open.tiktokapis.com/v1/oauth/token",
    userInfoUrl: "https://open.tiktokapis.com/v1/user/info/",
    scopes: ["user.info.basic"],
    defaultScopes: ["user.info.basic"],
  },
  pinterest: {
    id: "pinterest",
    name: "Pinterest",
    authorizationUrl: "https://api.pinterest.com/oauth/",
    tokenUrl: "https://api.pinterest.com/v1/oauth/token",
    userInfoUrl: "https://api.pinterest.com/v1/user/account",
    scopes: ["read_public"],
    defaultScopes: ["read_public"],
  },
  trello: {
    id: "trello",
    name: "Trello",
    authorizationUrl: "https://trello.com/1/authorize",
    tokenUrl: "https://api.trello.com/1/token",
    scopes: [],
    defaultScopes: [],
  },
  monday: {
    id: "monday",
    name: "Monday.com",
    authorizationUrl: "https://auth.monday.com/oauth2/authorize",
    tokenUrl: "https://auth.monday.com/oauth2/token",
    userInfoUrl: "https://api.monday.com/graphql",
    scopes: [],
    defaultScopes: [],
  },
  clickup: {
    id: "clickup",
    name: "ClickUp",
    authorizationUrl: "https://app.clickup.com/api",
    tokenUrl: "https://api.clickup.com/api/v2/oauth/token",
    userInfoUrl: "https://api.clickup.com/api/v2/user",
    scopes: [],
    defaultScopes: [],
  },
  box: {
    id: "box",
    name: "Box",
    authorizationUrl: "https://account.box.com/api/oauth2/authorize",
    tokenUrl: "https://api.box.com/oauth2/token",
    userInfoUrl: "https://api.box.com/2.0/users/me",
    scopes: [],
    defaultScopes: [],
  },
};

/**
 * Get OAuth provider config by ID
 */
export function getOAuthProvider(providerId: string): OAuthProviderConfig | undefined {
  return OAUTH_PROVIDERS[providerId.toLowerCase()];
}

/**
 * Get all OAuth provider IDs
 */
export function getAllOAuthProviderIds(): string[] {
  return Object.keys(OAUTH_PROVIDERS);
}
